# Generated by Django 5.0.6 on 2024-10-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('dbname', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('has_sedes', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('odoos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_commerces', to='wuasashop.odoo')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.JSONField(blank=True, default=dict)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('companie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_carts', to='wuasashop.commerce')),
                ('wuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_carts', to='wuasashop.wuser')),
            ],
        ),
        migrations.CreateModel(
            name='WUserCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wuasashop.commerce')),
                ('wuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commerces', to='wuasashop.wuser')),
            ],
        ),
        migrations.CreateModel(
            name='WUserOdoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('odoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wuasashop.odoo')),
                ('wuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odoos', to='wuasashop.wuser')),
            ],
        ),
        migrations.CreateModel(
            name='WUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wuasashop.role')),
                ('wuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='wuasashop.wuser')),
            ],
        ),
    ]
